site_name: Endeavour Wiki

theme:
  name: material
  icon:
    logo: material/alpha-e-circle
    repo: fontawesome/brands/github-square

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - stylesheets/custom.css

extra:
  social:
  - icon: fontawesome/brands/discord
    link: https://discord.gg/MVzHqdm
  - icon: fontawesome/brands/github
    link: https://github.com/greenfoot5/Endeavour

repo_url: https://github.com/greenfoot5/Endeavour-docs
repo_name: Greenfoot5/Endeavour-wiki

plugins:
  - git-revision-date